name: pqlserver

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 3

  qlds:
    image: pqlserver:latest
    stop_grace_period: 0s
    ports:
      - "27960:27960/udp"
      - "27960:27960/tcp"
    volumes:
      - ./data:/mnt/data
    environment:
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.qlds
    develop:
      watch:
        - path: ./Dockerfile.qlds
          action: rebuild
        - path: ./minqlx-plugins
          action: sync+restart
          target: /mnt/data/minqlx-plugins
